<?
ob_start();
?>
<h1>Weintek, таблица сравнения серий:<br>iP, iE, eMT, mTV, XE, cMT-SVR, cMT3151/3090/3072, cMT-G01/G02, cMT-HDMI/cMT-FHD
</h1>
<table id="kepka" class="compare_weintek_table1">
    <tbody>
    <tr>
        <td>
            <strong>Серия</strong>
        </td>
        <td>
            <strong>iP / iE</strong>
        </td>
        <td>
            <strong>eMT</strong>
        </td>
        <td>
            <strong>mTV</strong>
        </td>
        <td>
            <strong>XE</strong>
        </td>
        <td>
            <strong>cMT-SVR</strong>
        </td>
        <td>
            <span style="font-size: 11px;">
                <strong>cMT3071(72)</strong></span>
            <strong>3090/3151</strong>


        </td>
        <td>
            <strong>cMT3103</strong>
        </td>
        <td>
            <strong>cMT-G01/G02</strong>
            <strong>/G03/G04/</strong>
            <strong>/CTRL01/</strong>
        </td>
        <td>
            <strong>cMT-HDMI/cMT-FHD</strong>
        </td>
        <td>
            <span style="font-size: 10px;"><strong>cMT3161X(62)</strong></span>
            <strong>cMT3092X</strong>
            <strong>cMT3152X</strong>
        </td>
        <td>
            <strong>cMT3072X</strong>
            <strong>cMT3072XH</strong>
            <strong>cMT-FHDX-220</strong>

        </td>
        <td>
            <strong>cMT2078X</strong>
            <strong>cMT2108X</strong>
            <strong>cMT2158X</strong>
        </td>
    </tr>
    </tbody>
</table>

<table class="compare_weintek_table2">
    <tbody>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <th colspan="13" style="width: 100%">
            <strong>Ограничения памяти</strong>
        </th>
    </tr>
    <tr>
        <td>
            <strong>Project size limit</strong>
        </td>
        <td>
            22.5MB
        </td>
        <td>
            64MB
        </td>
        <td>
            64MB
        </td>
        <td>
            64MB
        </td>
        <td>
            32MB
        </td>
        <td>
            64MB
        </td>
        <td>
            64MB
        </td>
        <td>
            32MB
        </td>
        <td>
            64MB
        </td>
        <td>
            64MB
        </td>
        <td>
            64MB
        </td>
        <td>
            64MB
        </td>
    </tr>
    <tr>
        <td>
            <strong>History size limit</strong>
        </td>
        <td>
            16MB / 22MB
        </td>
        <td>
            64MB
        </td>
        <td>
            64MB
        </td>
        <td>
            64/120MB
        </td>
        <td>
            <a href="#note_1" title="Максимум: 40 выборок данных, 10000 записей в каждой">(*1)</a>
        </td>
        <td>
            <a href="#note_1" title="Максимум: 40 выборок данных, 10000 записей в каждой">(*1)</a>
        </td>
        <td>
            <a href="#note_1" title="Максимум: 40 выборок данных, 10000 записей в каждой">(*1)</a>
        </td>
        <td>
            Event Log
        </td>
        <td>
            <a href="#note_1" title="Максимум: 40 выборок данных, 10000 записей в каждой">(*1)</a>
        </td>
        <td>
            <a href="#note_1" title="Максимум: 40 выборок данных, 10000 записей в каждой">(*1)</a>
        </td>
        <td>
            <a href="#note_1" title="Максимум: 40 выборок данных, 10000 записей в каждой">(*1)</a>
        </td>
        <td>
            <a href="#note_1" title="Максимум: 40 выборок данных, 10000 записей в каждой">(*1)</a>
        </td>
    </tr>
    <tr>
        <th colspan="13" style="width: 100%">
            <strong>Загрузка проекта</strong>
        </th>
    </tr>

    <tr>
        <td>
            <strong>Build Data for USB Disk or SD Card Download</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>

    <tr>
        <td>
            <strong>USB Disk Download</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Project Protection</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <th colspan="13" style="width: 100%">
            <strong>Функциональные возможности</strong>
        </th>
    </tr>
    <tr>
        <td>
            <strong>3G/4G Dongle</strong>
        </td>
        <td>
            iP
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Audio (cMT Viewer)</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Touch Gesture</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            cMT3152X<br>
            cMT3162X<br>
            cMT3161X
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
    </tr>

    <tr>
        <td>
            <strong>Control Token</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>e-Mail</strong>
        </td>
        <td>
            iE
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Enhanced security mode</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Ethernet Printer</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Recipe Database</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>String Table</strong>
        </td>
        <td>
            iE
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Time Synchronization</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>USB Tethering</strong>
        </td>
        <td>
            iE
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>User-defined Startup Screen</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>VNC Server</strong>
        </td>
        <td>
           Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Web Streaming</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>WebView</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>



    <tr>
        <th colspan="13" style="width: 100%">
            <strong>Дополнительные интерфейсы</strong>
        </th>
    </tr>

    <tr>
        <td>
            <strong>Audio Output</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            только для 3120/3150
        </td>
        <td>
            через HDMI
        </td>
        <td>
            через USB
        </td>
        <td>
            N/A
        </td>
        <td>
            cMT3090
            cMT3151
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            через
            HDMI
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
          cMT2158X
        </td>
    </tr>
    <tr>
        <td>
            <strong>CAN Bus</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            MT8091/ MT8092XE
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            cMT3092X<br>
            cMT3152X<br>
            cMT3162X
        </td>
        <td>
            cMT3072XH
        </td>
        <td>
            N/A
        </td>
    </tr>

    <tr>
        <td><strong>MPI</strong></td>
<td>Y</td>
<td>Y</td>
<td>Y</td>
<td>Y</td>
<td>Y</td>
<td>Y</td>
<td>Y</td>
<td>Y</td>
<td>Y</td>
<td>Y</td>
<td>cMT3072XH, cMT-FHDX-220</td>
<td>Y</td>
    </tr>
    <tr>
        <td>
            <strong>Wi-Fi</strong>
        </td>
        <td>
           MT8103iE
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            только SVR200/202
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            только cMT-G02
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
    </tr>
    <tr>
        <td>
            <strong>Vibration Feedback</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            cMT3162X
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
    </tr>

    <tr>
        <th colspan="13" style="width: 100%">
            <strong>Доступные объекты в EasyBuilder</strong>
        </th>
    </tr>
    <tr>
        <td>
            <strong>Action Trigger</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            cMT3092X<br>
            cMT3152X<br>
            cMT3162X
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Barcode Scanner (Android Camera)</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            cMT3092X<br>
            cMT3152X<br>
            cMT3162X
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
    </tr>
    <tr>
        <td>
            <strong>Combo Button</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Date/Time</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Dynamic Drawing</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Dynamic Scale</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>File Browser</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Flow Block</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Media Player</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            eMT3105/
            3120/3150
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>PDF Reader</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Picture Viewer</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Operation Log Printing</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Operation Log View</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>

    <tr>
        <td>
            <strong>Recipe Import/Export</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Recipe View</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong><span>Table</span></strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong><span>PLC Web Browser</span></strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
          cMT3092X<br>
          cMT3152X<br>
          cMT3162X
        </td>
        <td>
           Y (кроме cMT-FHDX-220)
        </td>
        <td>
            N/A
        </td>
    </tr>
    <tr>
        <td>
            <strong>Video In - Video Input</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
    </tr>
    <tr>
        <td>
            <strong>Video In - IP Camera</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Video In - USB Camera</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <th colspan="13" style="width: 100%">
            <strong>Объекты IIoT и контроль энергопотребления</strong>
        </th>
    </tr>
    <tr>
        <td>
            <strong>Energy Demand Display</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            cMT3092X<br>
            cMT3152X<br>
            cMT3162X
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
    </tr>
    <tr>
        <td>
            <strong>Energy Demand Setting</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
    </tr>
    <tr>
        <td>
            <strong>MQTT publisher/subscriber</strong>
        </td>
        <td>
            iE
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>MQTT (AWS IoT, Sparkplug B, Azure IoT Hub)</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>OPC UA Server</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            License
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            License
        </td>
        <td>
            cMT3092X<br>
            cMT3152X<br>
            cMT3162X
        </td>
        <td>
            Y<br>
            (License для cMT-FHDX-220)
        </td>
        <td>
            N/A
        </td>
    </tr>
    <tr>
        <td>
            <strong>OPC UA Client</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <th colspan="13" style="width: 100%">
            <strong>Объекты работы с данными</strong>
        </th>
    </tr>
    <tr>
        <td>
            <strong>Circular Trend Display</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
    </tr>
    <tr>
        <td>
            <strong>BACnet Schedule</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            cMT3092X<br>
            cMT3152X<br>
            cMT3162X
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>



    <tr>
        <td>
            <strong>Database Server</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            cMT3092X<br>
            cMT3152X<br>
            cMT3162X
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
    </tr>
    <tr>
        <td>
            <strong>Event Bar Chart</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            cMT3092X<br>
            cMT3152X<br>
            cMT3162X
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
    </tr>
    <tr>
        <td>
            <strong>Operation Log Settings</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>SQL Query</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            cMT3162X<br>
            cMT3092X<br>
            cMT3152X
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
    </tr>
    <tr>
        <th colspan="13" style="width: 100%">
            <strong></strong>
        </th>
    </tr>
    <tr>
        <td>
            <strong>CODESYS</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            License
        </td>
        <td>
            N/A
        </td>
        <td>
            cMT-CTRL01
        </td>
        <td>
            N/A
        </td>
        <td>
            cMT3092X<br>
            cMT3152X<br>
            cMT3162X
        </td>
        <td>
            License
        </td>
        <td>
            License
        </td>
    </tr>
    <tr>
        <th colspan="13" style="width: 100%">
            <strong>Утилиты</strong>
        </th>
    </tr>
    <tr>
        <td>
            <strong>VNC Viewer</strong>
        </td>
        <td>
            iE
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>cMT Viewer - Diagnoser</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>EasyAccess 1.0</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
    </tr>
    <tr>
        <td>
            <strong>EasyAccess 2.0</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>Встроенная лицензия EasyAccess2.0 </strong>
        </td>
        <td>
            8053iE 8073iE 8103iE
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            8092XE
        </td>
        <td>
            SVR102 SVR202
        </td>
        <td>
            Y (кроме 3071)
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            cMT3092X<br>
            cMT3152X
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
    </tr>
    <tr>
        <td>
            <strong>EasyDiagnoser</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
    </tr>
    <tr>
        <td>
            <strong>EasyLauncher</strong>
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>EasyPrinter</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
    </tr>

    <tr>
        <td>
            <strong>EasySimulator</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
        <td>
            N/A
        </td>
    </tr>
    <tr>
        <td>
            <strong>EasySystemSetting</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            N/A
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <td>
            <strong>EasyWatch</strong>
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
        <td>
            Y
        </td>
    </tr>
    <tr>
        <th colspan="13" style="width: 100%">
<strong>Разное</strong>
        </th>
    </tr>

    <tr>
        <td>
            <strong>FTP-сервер</strong> - возможность удаленно забирать с панели журнал событий и выборок данных,
            обновлять рецепты
        </td>
        <td colspan="12">
            Имеется во всех панелях, оснащенных Ethernet-портом.
        </td>
    </tr>


    <tr>
        <th colspan="13" style="width: 100%">

        </th>
    </tr>
    </tbody>
</table>
<p id="note_1" style="font-size: 18px;">
    <strong>Примечание: </strong>
    *1. Максимум: 40 выборок данных, 10000 записей в каждой.
</p>
<table class="compare_weintek_table0">

    <tbody>
    <tr>
        <td>
            <ul>
                <li><strong>eMT Series:</strong> eMT3070B, eMT3105P, eMT3120A, eMT3150A</li>
                <li><strong>cMT Series:</strong> cMT-SVR-100, cMT-SVR-102, cMT-SVR-200, cMT-SVR-202, cMT-iV5, cMT3151, cMT3090, cMT3071, cMT3072, cMT3103,
cMT-HDM, cMT-FHD, cMT-FHDX-220
                </li>
                <li><strong>cMT X Series:</strong> cMT3092X, cMT3152X, cMT3072X, cMT3072XH, cMT3161X, cMT3162X, cMT2078X, cMT2108X, cMT2158X
                </li>
            </ul>
        </td>
        <td>
            <ul>
                <li><strong>mTV Series:</strong>mTV-100</li>
                <li><strong>iE Series:</strong> MT8050iE, MT8053iE, MT6070iE, MT6071iE, MT8070iE, MT8071iE, MT8073iE, MT8100iE, MT8101iE, MT8102iE, MT8103iE
                </li>
                <li><strong>iER Series:</strong> MT8070iER1</li>
            </ul>
        </td>
        <td>
            <ul>
                <li><strong>XE Series:</strong> MT8090XE, MT8091XE, MT8092XE, MT8121XE, MT8150XE</li>
                <li><strong>iP Series:</strong> MT6051iP, MT8051iP, MT6071iP, MT8071iP, MT6103iP, MT8102iP</li>
            </ul>
        </td>
    </tr>
    </tbody>
</table>

<?
$compare_weintek_table = ob_get_contents();
ob_end_clean();
?>
