<h1 id="Product_introduction">Product introduction</h1>
<hr>
<p>Haiwell PLC is a versatile high-performance programmable logic controller, which is widely used in plastics, packaging, textiles, food, medical, pharmaceutical, environmental, municipal, printing, building materials, elevators, central air conditioning, numerical control machine tools and other fields of systems and control equipment. In addition to its own various peripheral interfaces (digital input, digital output, analog input, analog output, high-speed counter, high-speed pulse output channels, power supply, communication ports, etc.), it can also extend all types of extension modules for flexible configuration.</p>
<p>HaiwellHappy programming software is a programming software which is in accordance with IEC 61131-3 standard. It can be used for Haiwell? PLC programming. Furthermore, it supports three kinds of programming languages--LD (Ladder Diagram), FBD (Function Block Diagram) and IL (Instruction List). It can run on the systems of Win98, Win200X, WinXP, Win7, Win8 and the later versions.</p>
<p><strong> Haiwell Cloud Platform</strong></p>
<p>Haiwell Cloud is a cross-platform IOT cloud platform. It supports PC, iPad, Android, IOS and other terminals. You can visit on-site equipments from a thousand miles away, and realize the remote monitoring and maintaining for HMI and PLC. It supports remote programming, firmware upgrades,monitoring and diagnosis ect.                                                                                                                                                                                    </p>
<p> Haiwell Cloud provides security mechanisms for communication. It is secured by the encryption mechanism of 128-bit SSL,which ensures the stable and safe data transfer. It also uses A-key and B-Key protection mechanism to enable secure remote access to the devices.</p>
<p></p>
<p><a data-fancybox href="<?= $path_to_images ?>images/Cloud.jpg"><img src="<?= $path_to_images ?>images/Cloud.jpg"/></a></p>
<br>
<h2 id="PLC_features">PLC features</h2>
<p><strong>1.</strong> <strong>Ethernet + : </strong>Host PLC and remote modules support Ethernet communication, host PLC support Ethernet port and 5 other RS232/RS485 communication ports working simultaniously,support N:N network type,support remote programming,debug, monitoring and data exchange. Easy to network with other PLC modules,HMI and PC via Ethernet port.</p>
<p><strong>2.</strong> <strong>The firmware upgrade function: </strong> Taking the lead in the function of realizing firmware upgrade in a small programmable controller. You can upgrade the system firmware through the firmware upgrade function free,therefore you bought the products previously can also have new features from Haiwell company.</p>
<p><strong>3.</strong> <strong>Rich network communication function: </strong> CPU host built two communication ports, which can be expandable to five communication ports, each port can be programmed and connects to network, and all of them can be used as masters or slaves. It can support 1: N, N: 1, N: N networking and a variety of man-machine interface and configuration software. It can also connect to network with any third-party devices which have communication capabilities (such as inverters, instruments, barcode readers, etc.).</p>
<p><strong>4.</strong> <strong>Supporting for multiple communication protocols:</strong>  It has internally installed Modbus RTU / ASCII protocol, Modbus TCP protocol, freedom communication protocol and the Haiwellbus, Haiwellbus TCP high-speed communication protocols of Xiamen Haiwell Technology Co.,Ltd.Owning to the most convenient communication instruction system, no matter what kind of communication protocols, it only simply needs a communication instruction when dealing with complex communication functions.You will no longer troubled by the problems, such as communications port? conflicts, sending and receiving control, communications interrupt handling issues and you can use a variety of protocols to exchange data easily by mixing them up in the program.</p>
<p><img style="float: right;margin: 0 0 15px 15px;" src="<?= $path_to_images ?>images/HHSC-16.jpg"  /> <strong>5. High-speed pulse counting function: </strong> Supports 8-channel duplex high-speed (200KHz) pulse counting, counting mode supports 7 kinds (pulse / direction 1 octave, pulse / direction 2 octave, forward / reverse pulse 1 octave, forward / reverse pulse 2 octave, A / B phase pulse 1 octave, A / B phase pulse 2 octave, A / B phase pulse 4 octave), and three kinds of comparisons (single-stage comparison, the absolute mode comparison, the relative mode comparision), supports 8 segments comparision fixed value, with self-learning function.</p>
<p><strong>6. High-speed pulse frequency measurement: </strong> Supports 16-channel (200KHz) high-speed pulse frequency measurement, support the ways of time or pulses to measure the frequency</p>
<p style="clear:both;"><img style="float: right;margin: 0 0 15px 15px;" src="<?= $path_to_images ?>images/PTO-16.jpg"  /><strong>7. High-speed pulse output: </strong> Supports 8-channel duplex high-speed (200KHz) pulse output, support for acceleration and deceleration pulse output, multi-segment envelope pulse output function, a unique sync pulse output function makes it easy to achieve precise synchronization control. Stand-alone support 16-channel pulse width modulation (PWM), can drive 16 servo or stepper motors.</p>
<p><strong>8. </strong> <strong>Motion control function: </strong>  Each model support for 8-channel(200KHZ) motion control, supports arbitrary 2-channel linear interpolation, circular interpolation, support follower pulse output, absolute address, relative address, backlash compensation, original point return, definition   of electrical origin.</p>
<p><strong>9. Edge capture and interrupts: </strong> CPU supports 8-channel up and down along the catch and interrupt functions, all digital inputs support signal filtering settings, all digital outputs remains set to support power output. Provide 52 real-time interrupt.</p>
<p><strong>10. Powerful analog processing function: </strong> AI register accesses the analog input directly, analog input support engineering conversion, sampling frequency settings, and zero correction. Available AQ registers control the analog output directly, analog output support engineering conversion and can be configured to maintain output.</p>
<p><strong>11. Strong password protection function: </strong> Three levels of password protection function (program files password, each block password, PLC hardware password) and prohibits the application to upload.</p>
<p> 12. <strong>Self-diagnostic function, power failure protection function, calendar (RTC), floating point operations, etc.</strong></p>
<br>
<h2 id="Programming_software_features">Programming software features</h2>
<p><img  style="display: block;margin: 15px auto 15px;" src="<?= $path_to_images ?>images/CloudRemote_en.jpg" /></p>
<p><strong>1. Haiwell Cloud Programming: </strong> Support Haiwell cloud platform, can use Haiwell cloud to do remote programming for Haiwell PLC, upload/download, firmware upgrade,self-diagnosis,monitor and debug. Easy for remote connection and  monitoring the real-time data of the site.</p>
<p><strong>2. Internal PLC simulator: </strong> Haiwell PLC programming software is the first one with internal simulator in China, realizing the PLC program run in the simulation.During programming or the programming is completed,you can run PLC program in the simulation without online to check the program execution is correct or not. It can reduce on-site commissioning time greatly, reduce debugging difficult and improve debugging efficiency.</p>
<p><strong>3. Communications simulator: </strong> It is used to the debug communication instruction simulation tools. It can be manually input simulately response message returned from salve, or you can use the computer's serial port to communicate with salve really, Simulate the process that PLC executes communication instruction really and process the return data from the salve.</p>
<img style="display: block;margin: 15px auto 15px;" src="<?= $path_to_images ?>images/CloudLocal_en.jpg" />
<p><strong>4. Interpolation simulator: </strong>Track and draw the trajectory generated from motion control instructions such as the linear interpolation, circular interpolation, listing parameters of the pulse output channel of the motive plane and corresponding to each axis, display the current position of the channel, the mechanical home position,output mode, you can set shaft length, unit pulses.</p>
<p><strong>5. Function of generate PLC executable file: </strong> PLC program can be generated to executable file which is released and executed independently.So you do not need to send the PLC program to the user,it can be very easy,very safe to put the PLC excutable file to the user to download,but do not worry the user would can see the program content.</p>
<p><strong>6. Facilitate innovation instruction set: </strong> On the basis of analysis and absorption of various PLC instruction, Haiwell PLC launched many powerful innovations facilitate instruction. As communication instruction (COMM, MODR, MODW, HWRD, HWWR), data portfolio diversification instruction (BUNB, BUNW, WUNW, BDIB, WDIB, WDIW), PID control (PID), valve control (VC), upper and lower alarm (HAL , LAL), range transmitter (SC), temperature curve (TTC) ,etc. Any one instruction can realize the function but other PLC required to multiple instructions.These instructions are very easy to understand and use, greatly improve the programming efficiency and running speed.</p>
<p><strong>7. Modular project structure: </strong>  Create 31 blocks total(main program, sub program, interrupt program) and chose any programming language to program. The execution order of block can be adjusted at random. Each block can be imported and exported independently and has the same password protected of program projects.So we can fully realize the modular programming and program reuse dreams.</p>
<p><strong>8. Instruction using table:</strong> Provides multiple instruction tables.Use these tables can reduce the amount of programs, saving program space, such as initialization data.Each table can be imported and exported independently and has the same password protection of program project.</p>
<p><strong>9. Powerful online features: </strong> Search out all the PLC that connect with the PC.Show running status, fault status, RUN / STOP switch position, hardware configuration information, communication port parameters such detailed information of all the online PLC.Select any PLC for online monitoring, program download,  firmware  upgrade, controlling PLC stop, adjusting PLC real-time clock, modifying password protection, modifying communication port parameters, modifying the watching-dog time and PLC station names.</p>
<p><strong>10. Online monitoring and debugging functions: </strong>  Provide 10 pages of component? monitoring table.It can choose in decimal, hexadecimal, binary, floating point and character to display data.Support component and register component monitoring hybridly and displaying component annotation at the same time.All instruction tables can be imported to the monitoring table.</p>
<p><strong>11. Unique real-time curve function: </strong> Monitor any register component for real-time curve to debug process-control facilitately.</p>
<p><strong>12. Humane input:</strong> Provide shortcuts, drag and drop, click and many other command input.Suggest effective components or range of values for each input and output terminals.It can be entered directly. Some data of combination (such as communication protocols etc.) can also double-click the  instruction   to configure the input data.</p>
<p><strong>13. Convenient annotation:</strong>Provide the component  comment,  network comment, instruction  comment, block  comment, table  comment, and project  comment.After the component with   "//" to input comments directly (eg: X0 // motor start).Comments can choose to download to the PLC for reading or modification facilitately.</p>
<p><strong>14. Detailed tips and online help: </strong> Provide PLC resource window,instruction window, etc.All the instructions and detailed description of hardware modules can be found in powerful online help system which is open through clicking F1 key in the programming interface to find the answer. Even if use HaiwellHappy programming software for the first time who can easily complete the preparation of control program.</p>
<p><strong>15. Convenient editing functions: </strong> Support all conventional editing operations, searching and replacing, instruction up and down, network up and down, copying and pasting between program projects.</p>
<p><strong> 16. Hardware configuration, sub program parameter passing, local components, indirection, print, preview, debugging, CRC calculation, password protection, etc.</strong></p>